apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas.replicaCount }}
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: employee
        ports:
        - containerPort: {{ .Values.service.internalport }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalport }}
  strategy:
    type: RollingUpdate
    rollingUp      maxSurge: 50%
